// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLy2DMiJ1-Qgzp5_xSTtzxGrsCIgzFrKo',
    appId: '1:760047474828:web:e28d53cad53a02a8ad43a9',
    messagingSenderId: '760047474828',
    projectId: 'supervisor-448ed',
    authDomain: 'supervisor-448ed.firebaseapp.com',
    storageBucket: 'supervisor-448ed.firebasestorage.app',
    measurementId: 'G-31YL2B2EEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFfowKHKHOUC-mJdQrc3JtSHk8wQgjDHs',
    appId: '1:760047474828:android:5f8649c8ce23a1b0ad43a9',
    messagingSenderId: '760047474828',
    projectId: 'supervisor-448ed',
    storageBucket: 'supervisor-448ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUzamZtil2Lk9uNw_6AAAn5ccJm4lcGRQ',
    appId: '1:760047474828:ios:45d8d0831e846a02ad43a9',
    messagingSenderId: '760047474828',
    projectId: 'supervisor-448ed',
    storageBucket: 'supervisor-448ed.firebasestorage.app',
    iosBundleId: 'com.proctoring.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUzamZtil2Lk9uNw_6AAAn5ccJm4lcGRQ',
    appId: '1:760047474828:ios:45d8d0831e846a02ad43a9',
    messagingSenderId: '760047474828',
    projectId: 'supervisor-448ed',
    storageBucket: 'supervisor-448ed.firebasestorage.app',
    iosBundleId: 'com.proctoring.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLy2DMiJ1-Qgzp5_xSTtzxGrsCIgzFrKo',
    appId: '1:760047474828:web:a186380e3e576563ad43a9',
    messagingSenderId: '760047474828',
    projectId: 'supervisor-448ed',
    authDomain: 'supervisor-448ed.firebaseapp.com',
    storageBucket: 'supervisor-448ed.firebasestorage.app',
    measurementId: 'G-5J5Y8D7K5V',
  );
}
